-- Create CUSTOMER Table
CREATE TABLE CUSTOMER (
    CustID NUMBER PRIMARY KEY,
    Name VARCHAR2(50) NOT NULL,
    Address VARCHAR2(100),
    Phone VARCHAR2(15)
);

-- Create PRODUCT Table
CREATE TABLE PRODUCT (
    ProdID NUMBER PRIMARY KEY,
    ProdName VARCHAR2(50) NOT NULL,
    Price NUMBER NOT NULL
);

-- Create ORDERS Table
CREATE TABLE ORDERS (
    OrderID NUMBER PRIMARY KEY,
    CustID NUMBER NOT NULL,
    ProdID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    CONSTRAINT FK_Customer FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID),
    CONSTRAINT FK_Product FOREIGN KEY (ProdID) REFERENCES PRODUCT(ProdID)
);
